version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: udiom
      POSTGRES_PASSWORD: udiom
  django:
    build: .
    volumes:
      - ./udiomproj:/udiomproj
    ports:
      - "80:80"
    depends_on:
      - postgres
