#!/usr/bin/env bash

# https://stackoverflow.com/a/42308482
# Wait for Postgres to start:
sleep 10

python /udiomproj/udiom/manage.py makemigrations userapp &>> runlog.txt
python /udiomproj/udiom/manage.py migrate &>> runlog.txt
python /udiomproj/udiom/manage.py runserver 0:80 &>> runlog.txt
